---
name: Guardian-OpenPlatform-API
version: 0.01
author:
  - 'Dave Cross, E<lt>dave@mag-sol.comE<gt>'
abstract: Access the Guardian OpenPlatform API
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP::UserAgent: 2.023
  Moose: 0
  perl: 5.006
build_requires:
  Test::More: 0.47
provides:
  Guardian::OpenPlatform::API:
    file: lib/Guardian/OpenPlatform/API.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
